FROM bellsoft/liberica-openjdk-alpine:17

# CMD ["./gradlew", "clean", "build"]

ARG JAR_FILE=build/libs/*.jar
# or Maven
# ARG JAR_FILE_PATH=target/*.jar

COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app.jar"]